### ISSUE TITLE
Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by EdithAllison** [ndiego/icon-block#12]
Sometimes I see in console: 

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <div>. See https://reactjs.org/link/warning-keys for more information.
div
No<@https://.../wp-content/plugins/icon-block/build/index.js?ver=0084d35570e783e202ca0d63d6e4ecad:2:6239
```

All maps have keys so I'm stumped why this error would occur.  It doesn't seem to break anything. 

PS: If it's of interest your plugin works perfectly with WP 6.0 Beta3, I've tested it today. 

_I updated the description of this issue to remove refereneces to my fork which turned out to be a separate issue & not linked to the missing keys._

**Comment by ndiego** [comment]
I have not been able to replicate it but will keep this issue open until the next release if anything pops up.

**Comment by ndiego** [comment]
I am still not able to replicate this issue. I have retested in 6.0 and 6.1 but have yet to be successful. Therefore, I am closing out this issue, but if anyone can reliably replicate it in 6.1, please feel free to comment, and I'll reopen.
