### ISSUE TITLE
Responsive support

### ISSUE THREAD

**Issue by zigojacko** [ndiego/icon-block#14]
Is there no support for mobiles/tablets? I'm not sure how to scale the icons for smaller screens...

**Comment by zigojacko** [comment]
Ah I see, if we use the icon width, then this populates the viewbox but when you set a percentage below this, the icons don't seem to scale... 🤷‍♂️

**Comment by ndiego** [comment]
#19 Should resolve this as you can now set the width of an icon using a variety of units, including `%`, `vh`, and `vw`. #20 also adds the same for height. Both PRs will be included in v1.4.0 due out next week.
