### ISSUE TITLE
Allow users to insert custom SVG icons from an "uploaded" .svg file

### ISSUE THREAD

**Issue by ndiego** [ndiego/icon-block#16]
Upgrade the placeholder component so that you can drop an .svg file onto the placeholder, and it will automatically insert the custom SVG. This functionality would be similar to the Image block placeholder, but the .svg is not actually uploaded. The SVG is just added to the custom SVG field. 

![upload](https://user-images.githubusercontent.com/4832319/193452046-f3a57496-5a74-4580-904a-db0ad24aa790.gif)

There should also be a way to do this in the custom SVG modal.

**Comment by nicmare** [comment]
YES!! like requested here https://wordpress.org/support/topic/upload-custom-svg-file-or-pick-on-from-media/
i could share a gist with my php svg validation code if you like
