### ISSUE TITLE
Allow more units for icon width

### ISSUE THREAD

**Issue by Jugibur** [ndiego/icon-block#17]
It would be great if you allowed more units than pixels. 
I'm a fan of "em" / "rem" so that the width adjusts to current font sizes. 
Of course it is always easier to use pixel units in a slider, but just allow the values to change in 0.1 steps and also add an input field so that you can really enter all values.

**Comment by Gierand** [comment]
Hi @ndiego,
Do you plan to add a field for custom units? It would be great to be able to add eg clamp(1rem, 5vw, 3rem).

Thank you for the well-thought-out plugin.
