### ISSUE TITLE
"wp-block-outermost-icon-block" / relative deep structure with text

### ISSUE THREAD

**Issue by Jugibur** [ndiego/icon-block#24]
Hi, 
I'm wondering why you have this relative deep structure just to show an svg.
I like to build a simple icon list (icon + text) but it's a bit inconvenient I think. You have to add a group, add icon plus text and rearrange both for perfect fit.

So after that the structure is:

- group-block
- wp-block-outermost-icon-block
- icon-container
- svg element

Perhaps I don't recognize why there is the outermost icon block.
Because it has a flex style my first thought was it's a kind of group, so I can just drag my text in it and have an icon + text.

That's my toughts about this. 
Perhaps you could improve this or could help what's the best way to reach my goal: a lightweight way for an icon + text list.
Thanks!

**Comment by ndiego** [comment]
Hi @Jugibur, I agree that the structure is deeper than would be ideal. However, it's needed to work well within the WordPress block architecture and allow for all the customization that the block supports. 

To create an icon list, I would use the Row block (a variation of the Group block) and then add an Icon block and a Paragraph block. However, this is not a "simple icon list" as you are looking for. You would probably need a custom-built block for this purpose.
