### ISSUE TITLE
Integrating with core/button

### ISSUE THREAD

**Issue by badg0003** [ndiego/icon-block#34]
Not sure if/how this would be possible, but since it's fairly common for CTAs to have some form of an icon associated with them it would be nice if this could be an option for the native `core/button`. I know there is the hacky insert-inline-image solution, but ideally having the option of picking from an available list of icons and then being able to position it to the left / right of the text would be great. Have you given any thought of doing that with your Icon Block or do the cons outweigh the pros?

**Comment by ndiego** [comment]
Thanks for logging this feature request @badg0003. Unfortunately, this is not possible with this block plugin. Entending the core Button block would need to be done in a separate plugin.
