### ISSUE TITLE
Feature Request: Allow Icons to be replaced in contentOnly mode

### ISSUE THREAD

**Issue by bacoords** [ndiego/icon-block#38]
When a template is in contentOnly mode, some media types (like images) can still be swapped out by the end user. I wonder if it would make sense for the Icon Block to offer the same functionality.

References: 
- `useBlockEditingMode` - https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockeditingmode

**Comment by ndiego** [comment]
This was added in cacd65bd18dfcd3d7676d3f8d865c06b660b5202 and https://github.com/ndiego/icon-block/commit/1b6e3f215e8dbc1159c5c62401f65fe9b2d0e3d1. `contentOnly` editing support will be available in the next release, likely next week.
