### ISSUE TITLE
Inconsistent Alphabetizing of Categories

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/icon-block#41]
While playing a bit more with categories and how they're sorted (https://github.com/ndiego/icon-block/issues/40), I noticed the following:

When you first open the Icon Library, our categories are sorted Alphabetically.

![2024-05-01 12_29_14-Edit Post ‹ Topic Hub — WordPress](https://github.com/ndiego/icon-block/assets/945157/aca61a74-c1ba-4cd3-bf39-275d6ffbebc4)

After engaging with a control, such as the Preview Size or the Search box, they become sorted as presented in our array.

![2024-05-01 12_29_36-Edit Post ‹ Topic Hub — WordPress](https://github.com/ndiego/icon-block/assets/945157/dcd5872b-446d-4d04-9d34-6ae2a4373c7c)

**Comment by ndiego** [comment]
This issue is fixed in [cdadf3a](https://github.com/ndiego/icon-block/commit/cdadf3a5c4c76e6bd93ae2eb8243178cc99c4ec1) and will be included in the next release.
