### ISSUE TITLE
Long Category names distort UI

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/icon-block#42]
When a category name gets on the longer side, it distorts the UI.  Perhaps it could wrap lines instead?

![2024-05-01 13_04_41-Edit Post ‹ Topic Hub — WordPress](https://github.com/ndiego/icon-block/assets/945157/794454cb-b250-4c3f-a6ac-9eb96173b1d2)

**Comment by ndiego** [comment]
This is fixed in [e6a6970](https://github.com/ndiego/icon-block/commit/e6a69705bb40df2f6e4786419906c020c0da65a5) and will be included in the next release.
