### ISSUE TITLE
"Icon color" control gets duplicated over and over on key press in Label (when Styles tab is disabled)

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/icon-block#43]
We have the Styles tab disabled, so that block Settings and Styles are all together. When this is the case, any key press in the Label input creates a duplicate Icon color control

![2024-05-02 14_49_43-Edit Post “Fill Test” ‹ Icon Block - Modless — WordPress](https://github.com/ndiego/icon-block/assets/945157/7bd07993-d325-4f63-b37a-7ac309a0aa6a)

**Comment by ndiego** [comment]
Thanks for reporting. This was fixed in [8b21f59](https://github.com/ndiego/icon-block/commit/8b21f59d1cdb029cc0821d276d8874e0d4a314eb) and will be included in the next release.
