### ISSUE TITLE
Horizontal Padding makes icon disappear (after first making the icon tiny)

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/icon-block#44]
I was playing with adding Padding to an Icon with a background color to increase the colored circle around it. Vertical padding seems to work as expected, but horizontal padding makes the icon disappear.

![2024-05-02 16_06_50-Window](https://github.com/ndiego/icon-block/assets/945157/8c5c9e19-3f53-4e8d-bb4d-06f377613ccc)

**Comment by ndiego** [comment]
This is expected because the icon container is contained by the width control. In hindsight, the width would have applied to the icon and not the container, but there were some major technical hurdles with this approach, and changing it now would be a pretty massive breaking change. 

The padding "breaking out" of the container when set to be larger than the width is annoying, but it's an inherent characteristic of CSS.

**Comment by MadtownLems** [comment]
Makes sense. In case anyone stumbles on this, here's what we're doing to disable Padding, since I can't really see much use to supporting it given how it works.

`function ext_icon_block_modifier_filter_metadata_registration( $metadata ) {
    
	if ( $metadata['name'] != 'outermost/icon-block' ) {
		return $metadata;
	}

	$metadata['supports']['spacing']['padding'] = false;
	
    return $metadata;
};
add_filter( 'block_type_metadata', 'ext_icon_block_modifier_filter_metadata_registration' );`

**Comment by ndiego** [comment]
Yeah not everyone needs padding, but the [Playground demo](https://playground.wordpress.net/?plugin=icon-block&blueprint-url=https://wordpress.org/plugins/wp-json/plugins/v1/plugin/icon-block/blueprint.json?rev=3057648) has a nice example of how useful it can be.

**Comment by MadtownLems** [comment]
Wow, that looks to behave very differently than our theme (and TT4).  It's also interesting how different the back and front ends look in the playground:

Back:
![2024-05-03 11_00_25-Window](https://github.com/ndiego/icon-block/assets/945157/87c0fbcc-545d-4573-abe8-568abe758483)


Front:
![2024-05-03 11_00_33-Window](https://github.com/ndiego/icon-block/assets/945157/38fbc690-1987-4c1d-a6a5-44cf35c7c416)

**Comment by ndiego** [comment]
Looks like something is up with your Playground instance. Styles don't look like they are loading based on the grey inserter.  This is what I am seeing and what it should look like:

| Editor | Frontend |
|-|-|
|<img width="700" alt="image" src="https://github.com/ndiego/icon-block/assets/4832319/ecce19d3-9d57-487f-abb5-838cc17d2fb2">|<img width="611" alt="image" src="https://github.com/ndiego/icon-block/assets/4832319/0ff5e5b9-87bc-4961-aa65-d8433a4b624e">

**Comment by MadtownLems** [comment]
> Looks like something is up with your Playground instance. Styles don't look like they are loading based on the grey inserter.

That checks out.  I don't use it much, so not sure what's causing that. Tried disabling adblockers but still no luck.

However, this has all been super helpful. I'm learning that Padding CAN be useful, but it will typically require growing the Icon size from the default in order to not have it disappear (crunched by the padding).  Thanks so much as always.
