### ISSUE TITLE
Feature Request: Support keywords 

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/icon-block#45]
Much like how Blocks can have invisible keywords that let them appear in a larger number of search results, it'd be great if Icons could as well.

For example, the Warning icon may want keywords such as "exclamation", or the Shipping icon might want 'truck'.

You never know what people are going to search for or how they'll 'remember' the name of an icon 😅

**Comment by ndiego** [comment]
Keywords are supported. Here's an [example](https://github.com/ndiego/icon-block/blob/fc7c7f0c2851c7146eb6d87aef86d9b6c106546a/src/icons/index.js#L444). Basically you can define an array of various keywords that are accounted for when searching.

**Comment by MadtownLems** [comment]
D'oh. I went to the documentation page just before making the issue and somehow completely missed it. Thank you! 🙏
