### ISSUE TITLE
Possible typo on a string

### ISSUE THREAD

**Issue by piermario** [ndiego/icon-block#46]
Hello! 

I'm working on the Italian localization of the Icon Block, and I stumbled upon a possible typo. 

One of the Justify icons says "Justify tretch", instead of - most likely - "Justify Stretch"

![Screenshot 2024-06-01 at 10 24 39](https://github.com/ndiego/icon-block/assets/1274831/b465f81a-4195-4ad2-b09e-60d010ad2f4e)

Can you please look into it?

Thanks!

**Comment by ndiego** [comment]
Yup, thanks for catching this! I have updated the string [here](https://github.com/ndiego/icon-block/commit/9b24168617bb8f5122cfd53e126a0b67b35efb67), and this will be included in the next release.

**Comment by piermario** [comment]
Great! Thank you Nick! :)
