### ISSUE TITLE
Add support for inline icon in the navigation block

### ISSUE THREAD

**Issue by imonareng** [ndiego/icon-block#48]
Hello Nick

It would be nice to be able to add inline icons to navigation items similar to how we can add inline images.

![Screenshot 2024-07-01 164835](https://github.com/ndiego/icon-block/assets/174355055/816f7f72-7ba0-41ae-ab4e-6df168e36ab0)

Cheers!

**Comment by ndiego** [comment]
Thanks for the suggestion. This plugin is purposefully designed to only add an Icon block; it can't add other Editor functionality. Cool idea for another plugin, though.
