### ISSUE TITLE
Add support for gradient coloring of the icon itself

### ISSUE THREAD

**Issue by saschafoerster** [ndiego/icon-block#49]
Right now, only the background can get a gradient color. I would like to color the icon itself in a gradient.

**Comment by ndiego** [comment]
Unfortunately, applying a gradient to the icon itself is not trivial after exploring a few different options. Given the different ways SVGs can be constructed, there is no singular solution. If you need a gradient on your icons, I recommend creating them in an application like Figma and then importing them as custom icons in the block.
