### ISSUE TITLE
Feature Request: Set default preview size (and maybe remember it?)

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/icon-block#51]
We find ourselves increasing the preview size pretty much every time we open the library, and find ourselves telling people they probably want to do the same.

Perhaps there could be a filter to set the default preview size?

Perhaps the last used preview size could be stored in local storage and used the next time an icon block library is opened?

**Comment by ndiego** [comment]
Added localStorage support for the preview size in the Icon Library in 14f93215428e8ec842bc2e05d76f73a0c1ef0e7b. This will be included in the next release.

**Comment by MadtownLems** [comment]
Testing this out. It's an improvement over not doing anything with remembering, for sure - but I did notice that if you open up a page with 2 icons on it, edit the first one, adjust the slider preview size, and then edit the other icon, it doesn't use the most recent slider size.

I think, in an ideal world, it would always update my preview size when I interact with the toggle, and always use that preview size whenever I open a control.  Not sure if that's viable though.

Thanks for adding support!
