### ISSUE TITLE
Preview Size Slider Incorrect on Re-opening

### ISSUE THREAD

**Issue by MadtownLems** [ndiego/icon-block#52]
Related to my last issue on preview size, I just realized the following:

If you open the library, and drag the Preview Size to very large, close the library, and reopen it....  the actual preview size will be remembered (large), but the slider will show it at the very left (small).  Interacting with the slider will get them in sync again.

**Comment by ndiego** [comment]
Somehow I missed this one, but good catch. I'll try fixing in the next release ahead of 6.7

**Comment by ndiego** [comment]
Fixed in https://github.com/ndiego/icon-block/commit/1cfe71be09c3e99668483b3b5d1b90ae22b9ddc6 and will be included in the next release.
