### ISSUE TITLE
Feature request: Add support for Page Link, Custom Link and Submenu blocks within the Navigation block

### ISSUE THREAD

**Issue by unscripted** [ndiego/icon-block#55]
As an admin, I need the ability to change the visibility of specific menu items based on the visibility controls applied in the block settings. 

I can't access the visibility controls for a Page Link, Custom Link or Submenu block, but I can access them for the Buttons, Page List, and Search blocks from within a navigation block.

I did not view this as a bug as I don't think this functionality previously existed. However, if it did, below are the steps to reproduce.

1. Go to Appearance > Editor > Navigation and select a navigation menu in the wp-admin.
2. Add a Page Link, Custom Link, Submenu, Page List, Button and Search block within the navigation block.
3. Check the block settings for each block added in the previous step to confirm the existence of the Visibility panel.

**Comment by ndiego** [comment]
Hi @unscripted, I'm guessing this is related to [Block Visibility](https://github.com/ndiego/block-visibility) and not the Icon Block, right? 

Regardless, if you enable Full Control Mode in the plugin settings, visibility conditions will be available for these blocks. By default, child blocks are disabled. 

<img width="785" alt="image" src="https://github.com/user-attachments/assets/a94f6196-db7a-457f-9b78-b9081c5a9f11">

**Comment by unscripted** [comment]
> I'm guessing this is related to Block Visibility and not the Icon Block

🤦🏻‍♂️

Thank you!
