### ISSUE TITLE
Feature Request: implement a more robust SVG sanitization

### ISSUE THREAD

**Issue by raphaelsuzuki** [ndiego/icon-block#56]
According to a comment in the code, the SVG sanitization process needs further improvement. This looks like a good candidate: https://github.com/darylldoyle/svg-sanitizer

It is already used by the Safe SVG plugin for WP, a popular module for Drupal and is implemented by default in Typo3.

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ndiego** [comment]
Thanks for sharing, but https://github.com/darylldoyle/svg-sanitizer is a PHP SVG/XML sanitizer, and anything implemented in this plugin would need to be in JavaScript.
