### ISSUE TITLE
Feature request : Could you please add support for emojis Please? 💡  

### ISSUE THREAD

**Issue by Hari-Bonda** [ndiego/icon-block#59]
I'm not sure if this feature is already available, but I wanted to add this light bulb emoji. While I could use an SVG as a workaround, it would be great if default emoji options were provided.  
Thank you for creating such an awesome plugin!

I have been through this page there is a way to add custom icons but its full of code i am not technical person, if there is an easy workaround please share
https://nickdiego.com/adding-custom-icons-to-the-icon-block/

https://chatgpt.com/share/674bcd24-db74-800b-a47b-ed3b1bf3e293

**Comment by ndiego** [comment]
Hi @Hari-Bonda. This plugin is designed specifically to display SVG icons. Adding emojis is not possible. That said, you can add emojis using a Paragraph block.
