### ISSUE TITLE
Blocks are broken in WordPress 5.8

### ISSUE THREAD

**Issue by t-hamano** [ndiego/icon-block#9]
Thanks for the great plugin.

I put it on **WordPress 5.8** and found that when I click on the "Brouse icon Library" button, the block breaks.

Please see:

https://user-images.githubusercontent.com/54422211/152667774-d316a50d-0974-40e0-bdce-5772b8d7dd16.mp4

I think this is because the SearchControl component has not been implemented in WordPress 5.8.

The `SearchControl` component was implemented in **Gutenberg 11.1.0**, but the version of Gutenberg included in WordPress 5.8 is **10.7**.

So you might want to replace it with a component such as `TextControl` if you will support WordPress 5.8.

**Comment by ndiego** [comment]
Hi @t-hamano, thank you for pointing this out! We plan to use additional functionality in 5.9, therefore I will push a release later this week with the new WordPress version requirement. If you prefer to use the 5.8 compatible version, I just attached the production ready v1.0.0 zip to the release: https://github.com/ndiego/icon-block/releases/tag/v1.0.0.

**Comment by t-hamano** [comment]
Thanks for the reply.
I will update my WordPress version to 5.9 and am looking forward to the new release of the plugin!

**Comment by ndiego** [comment]
The [latest release](https://wordpress.org/plugins/icon-block/) is now available so closing this out.
